# Generated by Django 2.0.7 on 2018-07-21 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rango', '0005_auto_20180702_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('page_id', models.ForeignKey(on_delete=False, to='rango.Page')),
                ('user_id', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'likes',
            },
        ),
    ]
