# Generated by Django 2.0.7 on 2018-07-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='page_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
    ]
