# Generated by Django 2.0.7 on 2018-07-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_auto_20180721_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='category',
            field=models.ForeignKey(on_delete=False, to='rango.Category'),
        ),
    ]
